version: "3.8"

services:
  machine_learning_lab:
    build: lab
    ports:
      - 8888:8888
    volumes:
      - ./lab/results:/home/jovyan/results:rw
      - ./lab/data:/home/jovyan/data:rw
      - ./lab/assets:/home/jovyan/assets:rw