version: "3.8"

services:
  machine_learning_lab:
    build: lab/.build
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=1
    volumes:
      - ./lab/data:/home/jovyan/data:rw
      - ./lab/docs:/home/jovyan/docs:rw
      - ./lab/libs:/home/jovyan/libs:rw
      - ./lab/models:/home/jovyan/models:rw
      - ./lab/results:/home/jovyan/results:rw
      - ./lab/notebooks:/home/jovyan/notebooks:rw
      - ./lab/personal-notebooks:/home/jovyan/personal-notebooks:rw