version: "3.7"

services:
  preprocessing:
    build: preprocessing/
    container_name: preprocessing
    environment:
      - GENERATE_NEW_DRAIN=yes
      - W2V_WINDOW_SIZE=5
      - W2V_EMBED_SIZE=512
      - NUM_NEG_SAMPLING=4
      - EPOCHS=25
    # runtime: nvidia
    volumes:
      - ./database:/database:ro
      - ./results:/results

  training:
    build: training/
    container_name: training
    environment:
      - W2V_EMBED_SIZE=512
      - EPOCHS=5
      - TRANSFORMER_LAYERS=4
      - TRANSFORMER_DFF=2048
      - TRANSFORMER_HEADS=8
      - DROPOUT_RATE=0.1
      - BATCH_SIZE=50
      - TRAINING=1
    volumes:
      - ./database:/database:ro
      - ./results:/results

  genmat:
    build: genmat/
    container_name: genmat
    environment:
      - TIME_FRAME=5
      - DB_PATH=/code/database/
    volumes:
      - ./database:/code/database:ro
      - ./results:/code/results

  dash:
    build: dash/
    container_name: dash
    volumes:
      - ./results:/code/results:ro
    ports:
      - "8050:8050"

  jupyter:
    build: 
      context: jupyter/
      args:
        - username=${username}
        - uid=${uid}
        - gid=${gid}
    container_name: jupyter
    environment: 
      - JUPYTER_ENABLE_LAB=yes  
    volumes:
      - ./results:/home/${username}/app/results
      - ./database:/home/${username}/app/data
      - ./assets:/home/${username}/app/assets
    ports:
      - "8888:8888"
      - "8050:8050"
    init: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility, compute]
