version: "3.8"

services:
  machine_learning_lab:
    image: samuel62/machine_learning_lab:mll_cuda_11.3.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=1
    volumes:
      - /home/dwalker/Development/personal_notebooks:/home/jovyan/notebooks