name: datascience

channels:
  - conda-forge
  - defaults

dependencies:
  - nodejs
  - git
  - jupyterlab>=3.0
  - jupyterlab-git
  - jupyterlab-lsp
  - pip
  - pip:
    - -r file:requirements.txt
  - xeus-python
  - python=3.8.6